### ISSUE TITLE
test(protocol-tree): 33 pane tests have been failing since the #471 MVC split

### ISSUE THREAD

**Issue by Vigne-hub** [Blue-Ocean-Technologies-Inc/Microdrop#663]
`pluggable_protocol_tree/tests/test_protocol_tree_pane.py` has **33 of its 83 tests failing on `main`**, and has done since #471. Every failure is the same shape — the test reaches for something that is no longer on `ProtocolTreePane`:

```
$ QT_QPA_PLATFORM=offscreen pixi run pytest pluggable_protocol_tree/tests/test_protocol_tree_pane.py -q
33 failed, 50 passed
```

| count | error |
|---|---|
| 7 | `'ProtocolTreePane' object has no attribute 'executor'` |
| 6 | `... no attribute '_run_completion_flow'` |
| 5 | `... no attribute '_on_protocol_terminated'` |
| 3 | `... no attribute 'logging_controller'` |
| 2 | `type object 'ProtocolTreePane' has no attribute '_format_error_html'` |
| 2 | `... no attribute '_on_protocol_started'` |
| 1 each | `_on_protocol_finished`, `navigate_to_first_step`, `navigate_to_last_step`, `module ... has no attribute 'information'`, `__init__() got an unexpected keyword argument 'executor_factory'`, one bare `assert None is not None` |

## Cause

`e36d830b` — *"MVC: move all run-control/handler logic from the pane to the dock pane (#471)"* — did exactly what it says. The pane's own comment now records the split:

> The dock pane owns the executor, the status controller, and all run control (issue #471). It drives these pure-view methods; the pane never touches the executor or status controller itself.

The tests were never moved with the logic. `6a1a8235` deleted 28 lines from this file, so the adaptation was started and then stopped.

## Why this matters

This is not 33 obsolete tests — it is **33 tests' worth of live behaviour that currently has no coverage at all**. The behaviour still exists; it just lives on `ProtocolTreeDockPane` in `pluggable_protocol_tree/views/dock_pane.py` now, and there is **no `test_dock_pane.py`**. What is silently unguarded:

- executor lifecycle and the `executor_factory` override
- the completion flow (finished / aborted / error / preview, autosave, experiment-manager-absent paths)
- pause/resume splitting the play button into phase nav, and phase-nav publishing `electrodes_state_change`
- `protocol_running` publishing and the `protocol_running_changed` signal
- error-dialog formatting and ordering (`_format_error_html`, dialog-before-completion-flow)
- report-flush progress dialog and worker behaviour
- logging controller start/stop

## Fix

Retarget the failing tests at `ProtocolTreeDockPane` — most should be a change of fixture and attribute owner, not a rewrite, since the assertions describe behaviour that still holds. Split them into a `test_dock_pane.py` and leave `test_protocol_tree_pane.py` covering only the pure-view surface it now has.

Anything that genuinely no longer exists should be deleted deliberately, with a note in the PR saying so — not left failing.

## Related

- Blocked open by #618 (run the pure-unit pytest partition in CI). With that gate in place this could not have gone unnoticed for as long as it has; conversely, #618 will go red on this file until this is fixed, so the two want sequencing.
- Same MVC split that #641 continues for the remaining controllers/services in `dock_pane` / `protocol_tree_pane`.

## Acceptance

- `pytest pluggable_protocol_tree/tests/test_protocol_tree_pane.py` is green
- The run-control behaviour listed above is covered against its current owner
- Any test deleted rather than moved is called out explicitly in the PR

_Filed with agent assistance (Claude Code). Found while verifying #574 — the failures are identical before and after that branch._

**Comment by Vigne-hub** [comment]
One thing to fold into the retargeting: a Brooks-Lint test scan on 2026-09-10 found `test_protocol_tree_pane.py` carries the suite's highest `assert_called*` count (14 sites, alongside 18 `MagicMock`/`patch` uses). While each test is being moved to `test_dock_pane.py`, check whether the assertion is on the call itself or on its exact args and order; keep the former where the call is the behaviour under test, and convert the latter to assertions on resulting state so the split does not carry over-specified tests into the new file.

_Comment added with agent assistance (Claude Code)._
